import type {
  Category,
  Collection,
  Occasion,
  Product,
  Review,
} from "./types";
import { standardProducts } from "./standard-data";

export const categories: Category[] = [
  { slug: "whiskey", name: "Whiskey", tagline: "Single malts & rare casks", hue: "#b5712f", count: 184 },
  { slug: "wine", name: "Wine", tagline: "Old-world estates", hue: "#7a1c2e", count: 312 },
  { slug: "champagne", name: "Champagne", tagline: "Grower & grande marque", hue: "#c8a24b", count: 96 },
  { slug: "vodka", name: "Vodka", tagline: "Crystalline & pure", hue: "#9fb6c4", count: 74 },
  { slug: "gin", name: "Gin", tagline: "Botanical artistry", hue: "#3f7d63", count: 88 },
  { slug: "rum", name: "Rum", tagline: "Aged in the tropics", hue: "#8a4422", count: 67 },
  { slug: "tequila", name: "Tequila", tagline: "Highland agave", hue: "#c9a86a", count: 59 },
  { slug: "craft-beer", name: "Craft Beer", tagline: "Small-batch brews", hue: "#caa13e", count: 121 },
  { slug: "gift-boxes", name: "Premium Gift Boxes", tagline: "Curated & wrapped", hue: "#6e1f2e", count: 43 },
];

export const products: Product[] = [
  {
    id: "p1",
    slug: "macallan-rare-cask-25",
    images: ["/bottles/macallan-rare-cask-25.png"],
    name: "Macallan Rare Cask 25",
    distillery: "The Macallan",
    category: "whiskey",
    categoryLabel: "Single Malt Whisky",
    price: 1850,
    compareAt: 2100,
    abv: 43,
    volume: "700ml",
    origin: "Speyside, Scotland",
    age: "25 Years",
    rating: 4.9,
    reviews: 214,
    palette: { glass: "#3a2412", liquid: "#9a4f1c", label: "#e9d8a6" },
    tags: ["Sherry Oak", "Collector", "Smooth"],
    tasting: {
      nose: "Dried fruits, vanilla, warm oak and a whisper of ginger.",
      palate: "Rich raisin, dark chocolate, candied orange and clove.",
      finish: "Long, velvet and gently spiced.",
    },
    notes: ["Raisin", "Dark Chocolate", "Orange", "Oak", "Clove"],
    pairings: ["Aged Manchego", "Dark chocolate truffles", "Roasted figs"],
    description:
      "A masterclass in sherry-seasoned oak maturation. Hand-selected casks deliver extraordinary depth, with a colour drawn entirely from the wood — never added.",
    badge: "Rare",
    stock: 6,
  },
  {
    id: "p2",
    slug: "dom-perignon-vintage",
    images: ["/bottles/dom-perignon-vintage.png"],
    name: "Dom Pérignon Vintage",
    distillery: "Dom Pérignon",
    category: "champagne",
    categoryLabel: "Vintage Champagne",
    price: 289,
    abv: 12.5,
    volume: "750ml",
    origin: "Épernay, France",
    rating: 4.8,
    reviews: 489,
    palette: { glass: "#1d2a1f", liquid: "#d8c878", label: "#0f1a12" },
    tags: ["Brut", "Celebration", "Vintage"],
    tasting: {
      nose: "White flowers, almond, candied citrus and toasted brioche.",
      palate: "Stone fruit, hazelnut, a saline minerality and fine mousse.",
      finish: "Crisp, elegant, persistent.",
    },
    notes: ["Brioche", "Almond", "Citrus", "White Flower"],
    pairings: ["Oysters", "Caviar", "Seared scallops"],
    description:
      "Only declared in exceptional years. A precise, luminous champagne built for celebration and ageing alike.",
    badge: "Best Seller",
    stock: 28,
  },
  {
    id: "p3",
    slug: "hibiki-harmony-master",
    images: [
      "/bottles/hibiki-harmony-master.png",
      "/bottles/life/whiskey-1.jpg",
      "/bottles/life/whiskey-2.jpg",
      "/bottles/life/whiskey-3.jpg",
    ],
    name: "Hibiki Harmony Master's Select",
    distillery: "Suntory",
    category: "whiskey",
    categoryLabel: "Blended Japanese Whisky",
    price: 320,
    abv: 43,
    volume: "700ml",
    origin: "Japan",
    rating: 4.9,
    reviews: 332,
    palette: { glass: "#2a1c10", liquid: "#c87a2a", label: "#f1e6cf" },
    tags: ["Blended", "Mizunara", "Refined"],
    tasting: {
      nose: "Honey, candied orange peel, rose and a hint of sandalwood.",
      palate: "Mizunara oak, white chocolate, ripe peach.",
      finish: "Subtle, sweet, gently woody.",
    },
    notes: ["Honey", "Orange Peel", "Rose", "Mizunara Oak"],
    pairings: ["Sushi", "Tempura", "Mochi"],
    description:
      "The art of Japanese blending — composed of malt and grain whiskies aged in a symphony of casks, including rare Mizunara oak.",
    badge: "Best Seller",
    stock: 19,
  },
  {
    id: "p4",
    slug: "opus-one-napa",
    images: ["/bottles/opus-one-napa.png"],
    name: "Opus One",
    distillery: "Opus One Winery",
    category: "wine",
    categoryLabel: "Bordeaux-Style Red Blend",
    price: 425,
    abv: 14.5,
    volume: "750ml",
    origin: "Napa Valley, USA",
    rating: 4.9,
    reviews: 176,
    palette: { glass: "#1a0a10", liquid: "#3d0d1a", label: "#d9c9a3" },
    tags: ["Cabernet", "Cellar", "Full-bodied"],
    tasting: {
      nose: "Blackcurrant, violet, graphite and cedar.",
      palate: "Velvety tannins, dark berry, espresso and tobacco leaf.",
      finish: "Profound and lingering.",
    },
    notes: ["Blackcurrant", "Violet", "Cedar", "Espresso"],
    pairings: ["Dry-aged ribeye", "Truffle risotto", "Hard cheeses"],
    description:
      "The legendary Mondavi–Rothschild collaboration. A seamless Napa expression of Bordeaux artistry, built to age for decades.",
    badge: "Award Winner",
    stock: 14,
  },
  {
    id: "p5",
    slug: "grey-goose-magnum",
    images: ["/bottles/grey-goose-magnum.png"],
    name: "Grey Goose Magnum",
    distillery: "Grey Goose",
    category: "vodka",
    categoryLabel: "Premium French Vodka",
    price: 96,
    abv: 40,
    volume: "1.5L",
    origin: "Cognac, France",
    rating: 4.7,
    reviews: 642,
    palette: { glass: "#10202b", liquid: "#dfeaf2", label: "#0c1822" },
    tags: ["Wheat", "Crystalline", "Party"],
    tasting: {
      nose: "Fresh, clean, faint almond and citrus.",
      palate: "Silky, soft wheat, a touch of white pepper.",
      finish: "Crisp and clean.",
    },
    notes: ["Soft Wheat", "Citrus", "White Pepper"],
    pairings: ["Martini", "Caviar", "Citrus cocktails"],
    description:
      "Distilled from single-origin Picardie wheat and blended with spring water from Cognac. A benchmark of clean, luxurious vodka.",
    badge: "Best Seller",
    stock: 54,
  },
  {
    id: "p6",
    slug: "monkey-47-gin",
    images: ["/bottles/monkey-47-gin.png"],
    name: "Monkey 47 Schwarzwald",
    distillery: "Black Forest Distillers",
    category: "gin",
    categoryLabel: "Dry Gin",
    price: 64,
    abv: 47,
    volume: "500ml",
    origin: "Black Forest, Germany",
    rating: 4.8,
    reviews: 388,
    palette: { glass: "#0f2419", liquid: "#cfe3d4", label: "#e8e0cd" },
    tags: ["47 Botanicals", "Complex", "Artisan"],
    tasting: {
      nose: "Juniper, lingonberry, citrus and pine.",
      palate: "Spruce, cardamom, bright fruit, peppery depth.",
      finish: "Long, herbal, faintly sweet.",
    },
    notes: ["Juniper", "Lingonberry", "Cardamom", "Pine"],
    pairings: ["Negroni", "Tonic & rosemary", "Smoked salmon"],
    description:
      "Forty-seven handpicked botanicals, many foraged from the Black Forest, married with mountain spring water for unmatched complexity.",
    badge: "New",
    stock: 31,
  },
  {
    id: "p7",
    slug: "diplomatico-reserva",
    images: ["/bottles/diplomatico-reserva.png"],
    name: "Diplomático Reserva Exclusiva",
    distillery: "Destilerías Unidas",
    category: "rum",
    categoryLabel: "Aged Dark Rum",
    price: 58,
    abv: 40,
    volume: "700ml",
    origin: "Venezuela",
    age: "12 Years",
    rating: 4.8,
    reviews: 421,
    palette: { glass: "#1d0f08", liquid: "#7a3812", label: "#e2c98f" },
    tags: ["Aged", "Sipping", "Sweet"],
    tasting: {
      nose: "Toffee, orange peel, brown sugar and oak.",
      palate: "Maple, dark chocolate, liquorice and warm spice.",
      finish: "Smooth, long, dessert-like.",
    },
    notes: ["Toffee", "Maple", "Dark Chocolate", "Spice"],
    pairings: ["Crème brûlée", "Cigars", "Dark chocolate"],
    description:
      "Aged up to twelve years in small batches. A sumptuous sipping rum that drinks like dessert in a glass.",
    badge: "Best Seller",
    stock: 47,
  },
  {
    id: "p8",
    slug: "clase-azul-reposado",
    images: ["/bottles/clase-azul-reposado.png"],
    name: "Clase Azul Reposado",
    distillery: "Clase Azul",
    category: "tequila",
    categoryLabel: "Reposado Tequila",
    price: 189,
    abv: 40,
    volume: "750ml",
    origin: "Jalisco, Mexico",
    rating: 4.9,
    reviews: 297,
    palette: { glass: "#0e2740", liquid: "#dcc079", label: "#f2f4f7" },
    tags: ["Agave", "Hand-painted", "Collector"],
    tasting: {
      nose: "Cooked agave, vanilla, caramel and oak.",
      palate: "Buttery agave, toasted almond, soft spice.",
      finish: "Warm, smooth, elegant.",
    },
    notes: ["Cooked Agave", "Vanilla", "Caramel", "Almond"],
    pairings: ["Ceviche", "Grilled corn", "Dark chocolate"],
    description:
      "Rested eight months in oak and presented in an iconic hand-painted decanter — each one a unique work of Mexican ceramic art.",
    badge: "Limited",
    stock: 11,
  },
  {
    id: "p9",
    slug: "yamazaki-18",
    images: ["/bottles/yamazaki-18.png"],
    name: "Yamazaki 18 Year",
    distillery: "Suntory",
    category: "whiskey",
    categoryLabel: "Single Malt Japanese Whisky",
    price: 1450,
    abv: 43,
    volume: "700ml",
    origin: "Japan",
    age: "18 Years",
    rating: 5.0,
    reviews: 142,
    palette: { glass: "#2a160c", liquid: "#a8521a", label: "#efe2c4" },
    tags: ["Sherry Cask", "Rare", "Award Winner"],
    tasting: {
      nose: "Dried fruit, mizunara incense, dark berries.",
      palate: "Raisin, blackberry, sweet spice and deep oak.",
      finish: "Profound, layered, exceptionally long.",
    },
    notes: ["Dried Fruit", "Blackberry", "Incense", "Oak"],
    pairings: ["Wagyu", "Aged cheese", "Dark chocolate"],
    description:
      "A pinnacle of Japanese whisky, matured in sherry, American and rare Mizunara oak. Profound and endlessly rewarding.",
    badge: "Rare",
    stock: 4,
  },
  {
    id: "p10",
    slug: "sassicaia-bolgheri",
    images: ["/bottles/sassicaia-bolgheri.png"],
    name: "Sassicaia Bolgheri",
    distillery: "Tenuta San Guido",
    category: "wine",
    categoryLabel: "Super Tuscan Red",
    price: 365,
    abv: 14,
    volume: "750ml",
    origin: "Tuscany, Italy",
    rating: 4.9,
    reviews: 203,
    palette: { glass: "#160810", liquid: "#3a0f1c", label: "#cdb98c" },
    tags: ["Super Tuscan", "Cellar", "Elegant"],
    tasting: {
      nose: "Cassis, mint, cedar and Mediterranean herbs.",
      palate: "Refined tannins, red cherry, graphite, spice.",
      finish: "Silken and sustained.",
    },
    notes: ["Cassis", "Mint", "Cedar", "Cherry"],
    pairings: ["Bistecca alla Fiorentina", "Wild boar ragù", "Pecorino"],
    description:
      "The wine that defined the Super Tuscan movement. Coastal elegance, structure and grace from the Bolgheri shoreline.",
    badge: "Award Winner",
    stock: 22,
  },
  {
    id: "p11",
    slug: "krug-grande-cuvee",
    images: ["/bottles/krug-grande-cuvee.png"],
    name: "Krug Grande Cuvée",
    distillery: "Krug",
    category: "champagne",
    categoryLabel: "Prestige Champagne",
    price: 245,
    abv: 12,
    volume: "750ml",
    origin: "Reims, France",
    rating: 4.9,
    reviews: 168,
    palette: { glass: "#241a08", liquid: "#e4cf86", label: "#0e0a04" },
    tags: ["Prestige", "Multi-Vintage", "Rich"],
    tasting: {
      nose: "Toasted nuts, honey, dried fruit and brioche.",
      palate: "Marzipan, citrus zest, gingerbread, fine bubbles.",
      finish: "Opulent and remarkably long.",
    },
    notes: ["Hazelnut", "Honey", "Marzipan", "Citrus"],
    pairings: ["Lobster", "Aged comté", "Roast chicken"],
    description:
      "A blend of more than 120 wines across many vintages — the fullest expression of champagne, recreated in harmony each year.",
    badge: "Limited",
    stock: 17,
  },
  {
    id: "p12",
    slug: "bottleexpress-reserve-trilogy",
    name: "BottleExpress Reserve Trilogy",
    distillery: "BottleExpress Atelier",
    category: "gift-boxes",
    categoryLabel: "Curated Gift Box",
    price: 540,
    compareAt: 620,
    abv: 0,
    volume: "3 × 200ml",
    origin: "Curated Worldwide",
    rating: 5.0,
    reviews: 88,
    palette: { glass: "#1a0c12", liquid: "#6e1f2e", label: "#e9d8a6" },
    tags: ["Gift", "Curated", "Tasting Set"],
    tasting: {
      nose: "A guided journey across three flagship spirits.",
      palate: "Whisky, aged rum and reposado tequila in miniature.",
      finish: "An unforgettable gifting experience.",
    },
    notes: ["Whisky", "Aged Rum", "Reposado", "Tasting Notes"],
    pairings: ["Anniversaries", "Corporate gifting", "Connoisseurs"],
    description:
      "Three of our most celebrated pours presented in a magnetic lacquered case with hand-letterpressed tasting cards and gold ritual tools.",
    badge: "New",
    stock: 25,
  },
];

/** Standard storefront catalog (everyday bottles) — kept separate from premium. */
export { standardProducts };

/** Premium + standard combined — used for slug lookups and DB seeding. */
export const allProducts: Product[] = [...products, ...standardProducts];

export const bestSellers = products.filter((p) =>
  ["p2", "p3", "p5", "p7", "p1", "p8"].includes(p.id)
);

/** Top everyday picks for the standard storefront. */
export const standardBestSellers = standardProducts.filter((p) =>
  p.badge === "Best Seller"
);

export const collections: Collection[] = [
  { slug: "rare-whiskeys", title: "Rare Whiskeys", subtitle: "Allocated single casks & aged expressions", accent: "#b5712f", count: 42 },
  { slug: "collectors-editions", title: "Collector's Editions", subtitle: "Numbered bottlings & decanters", accent: "#c8a24b", count: 28 },
  { slug: "imported-wines", title: "Imported Wines", subtitle: "Old-world estates, hand-selected", accent: "#7a1c2e", count: 64 },
  { slug: "luxury-gift-packs", title: "Luxury Gift Packs", subtitle: "Wrapped, ribboned & ready", accent: "#1c5c46", count: 31 },
  { slug: "limited-releases", title: "Limited Releases", subtitle: "Here today, allocated tomorrow", accent: "#6e1f2e", count: 19 },
];

export const occasions: Occasion[] = [
  { slug: "party", title: "Party Collection", blurb: "Crowd-pleasing pours & magnums", accent: "#6e1f2e" },
  { slug: "wedding", title: "Wedding Collection", blurb: "Champagne towers & toasts", accent: "#c8a24b" },
  { slug: "corporate", title: "Corporate Gifting", blurb: "Branded, bulk & beautiful", accent: "#1c5c46" },
  { slug: "anniversary", title: "Anniversary Collection", blurb: "Vintages from their year", accent: "#7a1c2e" },
  { slug: "celebration", title: "Celebration Collection", blurb: "For every milestone moment", accent: "#b5712f" },
];

export const reviews: Review[] = [
  {
    id: "r1",
    name: "Alexandra Vance",
    location: "New York, NY",
    rating: 5,
    title: "Concierge service, truly",
    body: "The bottle arrived chilled, gift-wrapped, and within ninety minutes. It felt like ordering from a private cellar, not an app.",
    product: "Dom Pérignon Vintage",
    verified: true,
  },
  {
    id: "r2",
    name: "Marcus Reed",
    location: "London, UK",
    rating: 5,
    title: "Finally, a Yamazaki 18",
    body: "I've been hunting this for two years. BottleExpress sourced it, authenticated it, and delivered in original packaging. Flawless.",
    product: "Yamazaki 18 Year",
    verified: true,
  },
  {
    id: "r3",
    name: "Priya Nair",
    location: "Dubai, UAE",
    rating: 5,
    title: "The gift box is art",
    body: "Sent the Reserve Trilogy to a client. The lacquered case and letterpress cards made an impression no email ever could.",
    product: "BottleExpress Reserve Trilogy",
    verified: true,
  },
  {
    id: "r4",
    name: "Thomas Béland",
    location: "Paris, FR",
    rating: 5,
    title: "VIP membership pays for itself",
    body: "Early access to allocated bottles alone is worth it. Priority delivery and member pricing are the cherry on top.",
    product: "VIP Membership",
    verified: true,
  },
  {
    id: "r5",
    name: "Sofia Romano",
    location: "Milan, IT",
    rating: 5,
    title: "A wine list I trust",
    body: "Every Italian label I've ordered has been stored and shipped perfectly. The Sassicaia was singing on arrival.",
    product: "Sassicaia Bolgheri",
    verified: true,
  },
  {
    id: "r6",
    name: "James Whitlock",
    location: "Singapore",
    rating: 5,
    title: "Effortless, elegant",
    body: "The whole experience — browsing, tasting notes, checkout, tracking — feels like a luxury house, not a liquor store.",
    product: "Hibiki Harmony",
    verified: true,
  },
];

export function getProduct(slug: string) {
  return allProducts.find((p) => p.slug === slug);
}

export function relatedProducts(product: Product) {
  // Stay within the same storefront segment as the product.
  const segment = product.segment ?? "PREMIUM";
  const pool = allProducts.filter((p) => (p.segment ?? "PREMIUM") === segment);
  return pool
    .filter((p) => p.category === product.category && p.id !== product.id)
    .concat(pool.filter((p) => p.category !== product.category && p.id !== product.id))
    .slice(0, 4);
}
