// AUTO-GENERATED by the media refresh — single transparent bottle photo per product.
export const STANDARD_MEDIA: Record<string, { images: string[]; video: string | null }> = {
  "agave-sol-blanco": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160241/nocturne/standard/agave-sol-blanco.png"
    ],
    "video": null
  },
  "casa-verde-reposado": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160250/nocturne/standard/casa-verde-reposado.png"
    ],
    "video": null
  },
  "citrus-grove-gin": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160256/nocturne/standard/citrus-grove-gin.png"
    ],
    "video": null
  },
  "citrus-twist-vodka": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160262/nocturne/standard/citrus-twist-vodka.png"
    ],
    "video": null
  },
  "coastal-sauvignon-blanc": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160284/nocturne/standard/coastal-sauvignon-blanc.png"
    ],
    "video": null
  },
  "copper-trail-ipa": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160291/nocturne/standard/copper-trail-ipa.png"
    ],
    "video": null
  },
  "crisp-pilsner": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160298/nocturne/standard/crisp-pilsner.png"
    ],
    "video": null
  },
  "dark-cove-rum": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160310/nocturne/standard/dark-cove-rum.png"
    ],
    "video": null
  },
  "garden-botanical-gin": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160320/nocturne/standard/garden-botanical-gin.png"
    ],
    "video": null
  },
  "garnet-merlot": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160328/nocturne/standard/garnet-merlot.png"
    ],
    "video": null
  },
  "glacier-clear-vodka": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160337/nocturne/standard/glacier-clear-vodka.png"
    ],
    "video": null
  },
  "golden-wheat-ale": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160352/nocturne/standard/golden-wheat-ale.png"
    ],
    "video": null
  },
  "harbor-lager": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160360/nocturne/standard/harbor-lager.png"
    ],
    "video": null
  },
  "highland-blend-whisky": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160367/nocturne/standard/highland-blend-whisky.png"
    ],
    "video": null
  },
  "island-gold-rum": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160374/nocturne/standard/island-gold-rum.png"
    ],
    "video": null
  },
  "lime-fields-tequila": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160380/nocturne/standard/lime-fields-tequila.png"
    ],
    "video": null
  },
  "london-dry-gin": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160395/nocturne/standard/london-dry-gin.png"
    ],
    "video": null
  },
  "midnight-cabernet": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160402/nocturne/standard/midnight-cabernet.png"
    ],
    "video": null
  },
  "midnight-oats-stout": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160412/nocturne/standard/midnight-oats-stout.png"
    ],
    "video": null
  },
  "northern-pure-vodka": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160419/nocturne/standard/northern-pure-vodka.png"
    ],
    "video": null
  },
  "oak-ridge-chardonnay": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160427/nocturne/standard/oak-ridge-chardonnay.png"
    ],
    "video": null
  },
  "old-mill-bourbon": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160440/nocturne/standard/old-mill-bourbon.png"
    ],
    "video": null
  },
  "riverside-rye": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160445/nocturne/standard/riverside-rye.png"
    ],
    "video": null
  },
  "rose-bloom": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160454/nocturne/standard/rose-bloom.png"
    ],
    "video": null
  },
  "silver-birch-vodka": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160463/nocturne/standard/silver-birch-vodka.png"
    ],
    "video": null
  },
  "smoky-peat-whisky": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160472/nocturne/standard/smoky-peat-whisky.png"
    ],
    "video": null
  },
  "spiced-harbor-rum": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160477/nocturne/standard/spiced-harbor-rum.png"
    ],
    "video": null
  },
  "sunset-pale-ale": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160487/nocturne/standard/sunset-pale-ale.png"
    ],
    "video": null
  },
  "tuscan-table-red": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160505/nocturne/standard/tuscan-table-red.png"
    ],
    "video": null
  },
  "valley-red-blend": {
    "images": [
      "https://res.cloudinary.com/dvt8qhmnx/image/upload/v1781160525/nocturne/standard/valley-red-blend.png"
    ],
    "video": null
  }
};
