import type { Product, CategorySlug } from "./types";
import { STANDARD_MEDIA } from "./standard-media";

/**
 * Standard storefront catalog — everyday, value-focused bottles.
 * Kept fully separate from the premium catalog (no overlap). Media (4 photos +
 * a slideshow video per product) is hosted on Cloudinary — see
 * standard-media.ts (generated by scripts/upload-standard-cloudinary.ts).
 */

const LABELS: Record<CategorySlug, string> = {
  whiskey: "Whisky",
  wine: "Wine",
  champagne: "Sparkling",
  vodka: "Vodka",
  gin: "Gin",
  rum: "Rum",
  tequila: "Tequila",
  "craft-beer": "Beer",
  "gift-boxes": "Gift Pack",
};

type Raw = {
  slug: string;
  name: string;
  category: CategorySlug;
  distillery: string;
  price: number;
  compareAt?: number;
  abv: number;
  volume: string;
  origin: string;
  rating: number;
  reviews: number;
  stock: number;
  badge?: Product["badge"];
  palette: { glass: string; liquid: string; label: string };
  tags: string[];
  tasting: { nose: string; palate: string; finish: string };
  notes: string[];
  pairings: string[];
  description: string;
  /* optional media overrides (otherwise resolved from STANDARD_MEDIA) */
  images?: string[];
  video?: string;
};

const raw: Raw[] = [
  // ---------- Beer ----------
  { slug: "harbor-lager", name: "Harbor Lager", category: "craft-beer", distillery: "Harbor Brewing Co.", price: 11, abv: 4.6, volume: "6 × 330ml", origin: "Portland, USA", rating: 4.4, reviews: 312, stock: 240, badge: "Best Seller", palette: { glass: "#3a2e0c", liquid: "#e0a92b", label: "#c8102e" }, tags: ["Crisp", "Easy", "Sessionable"], tasting: { nose: "Fresh bread and a touch of citrus hops.", palate: "Clean malt, light bitterness, very drinkable.", finish: "Short, crisp and refreshing." }, notes: ["Malt", "Citrus", "Bread"], pairings: ["Burgers", "Pizza", "Wings"], description: "A crisp everyday lager built for the cooler. Clean, refreshing and easy on the wallet." },
  { slug: "copper-trail-ipa", name: "Copper Trail IPA", category: "craft-beer", distillery: "Copper Trail", price: 13, abv: 6.5, volume: "6 × 330ml", origin: "Denver, USA", rating: 4.5, reviews: 268, stock: 180, palette: { glass: "#2e1c06", liquid: "#c9742a", label: "#1c6b3a" }, tags: ["Hoppy", "Citrus", "Bold"], tasting: { nose: "Grapefruit, pine and tropical hops.", palate: "Juicy citrus with a firm bitter backbone.", finish: "Dry, resinous and bold." }, notes: ["Grapefruit", "Pine", "Mango"], pairings: ["Spicy tacos", "Aged cheddar", "BBQ"], description: "A punchy, hop-forward IPA for everyday hop lovers. Big citrus, easy price." },
  { slug: "midnight-oats-stout", name: "Midnight Oats Stout", category: "craft-beer", distillery: "Cellar Door", price: 12, abv: 5.8, volume: "4 × 440ml", origin: "Dublin, Ireland", rating: 4.6, reviews: 201, palette: { glass: "#120a06", liquid: "#1a0f08", label: "#caa13e" }, tags: ["Roasty", "Smooth", "Creamy"], tasting: { nose: "Coffee, cocoa and toasted oats.", palate: "Silky, roasty and gently sweet.", finish: "Long, chocolatey and smooth." }, notes: ["Coffee", "Cocoa", "Oats"], stock: 150, pairings: ["Chocolate cake", "Oysters", "Stew"], description: "A smooth, creamy oatmeal stout — coffee and cocoa for the price of a pint." },
  { slug: "golden-wheat-ale", name: "Golden Wheat Ale", category: "craft-beer", distillery: "Meadow & Vine", price: 10, abv: 5.0, volume: "6 × 330ml", origin: "Munich, Germany", rating: 4.3, reviews: 176, stock: 210, palette: { glass: "#3a2e0c", liquid: "#e8c25a", label: "#2b5fa6" }, tags: ["Wheat", "Zesty", "Light"], tasting: { nose: "Banana, clove and soft wheat.", palate: "Light, zesty and slightly fruity.", finish: "Clean and gently spiced." }, notes: ["Banana", "Clove", "Wheat"], pairings: ["Salads", "Grilled fish", "Pretzels"], description: "A bright, zesty wheat ale — a light everyday pour for warm afternoons." },
  { slug: "sunset-pale-ale", name: "Sunset Pale Ale", category: "craft-beer", distillery: "Coastline Brews", price: 12, abv: 5.2, volume: "6 × 330ml", origin: "San Diego, USA", rating: 4.4, reviews: 233, stock: 195, palette: { glass: "#2e1c06", liquid: "#d98a2b", label: "#e8543d" }, tags: ["Balanced", "Citrus", "Smooth"], tasting: { nose: "Orange peel and light caramel.", palate: "Balanced malt and hops, smooth body.", finish: "Mellow and refreshing." }, notes: ["Orange", "Caramel", "Hops"], pairings: ["Tacos", "Chicken", "Fries"], description: "An easy-drinking pale ale that balances malt and hops for everyday enjoyment." },
  { slug: "crisp-pilsner", name: "Crisp Pilsner", category: "craft-beer", distillery: "Old Town Brewery", price: 10, abv: 4.8, volume: "6 × 330ml", origin: "Plzeň, Czechia", rating: 4.5, reviews: 289, badge: "Best Seller", stock: 260, palette: { glass: "#3a2e0c", liquid: "#edcf6a", label: "#1f6f4a" }, tags: ["Crisp", "Clean", "Classic"], tasting: { nose: "Floral hops and fresh straw.", palate: "Crisp, clean and lightly bitter.", finish: "Dry and snappy." }, notes: ["Floral", "Straw", "Malt"], pairings: ["Schnitzel", "Sausages", "Salads"], description: "A classic crisp pilsner — clean, golden and endlessly refreshing." },

  // ---------- Vodka ----------
  { slug: "northern-pure-vodka", name: "Northern Pure Vodka", category: "vodka", distillery: "Northern Distillers", price: 22, abv: 40, volume: "700ml", origin: "Sweden", rating: 4.4, reviews: 410, badge: "Best Seller", stock: 120, palette: { glass: "#13202b", liquid: "#eef4f8", label: "#1b3a52" }, tags: ["Smooth", "Clean", "Mixable"], tasting: { nose: "Neutral with a faint grain sweetness.", palate: "Smooth, clean and soft.", finish: "Crisp and short." }, notes: ["Grain", "Clean", "Pepper"], pairings: ["Mixers", "Cocktails", "Chilled shots"], description: "A clean, smooth everyday vodka that mixes effortlessly. Triple-distilled value." },
  { slug: "silver-birch-vodka", name: "Silver Birch Vodka", category: "vodka", distillery: "Birchwood Co.", price: 19, abv: 40, volume: "700ml", origin: "Poland", rating: 4.3, reviews: 322, stock: 140, palette: { glass: "#13202b", liquid: "#f2f6f9", label: "#5b6e7a" }, tags: ["Soft", "Value", "Versatile"], tasting: { nose: "Subtle and clean.", palate: "Light, soft and easy.", finish: "Quick and smooth." }, notes: ["Clean", "Soft", "Mineral"], pairings: ["Tonic", "Juice", "Soda"], description: "An honest, soft vodka for everyday cocktails — great value, no fuss." },
  { slug: "glacier-clear-vodka", name: "Glacier Clear Vodka", category: "vodka", distillery: "Glacier Spirits", price: 26, abv: 40, volume: "700ml", origin: "Finland", rating: 4.5, reviews: 298, stock: 110, palette: { glass: "#13202b", liquid: "#eaf3f8", label: "#2e7fb0" }, tags: ["Crisp", "Pure", "Cold"], tasting: { nose: "Pure and crisp.", palate: "Clean, cold and silky.", finish: "Dry and clean." }, notes: ["Pure", "Crisp", "Silk"], pairings: ["Martini", "Neat", "Mixers"], description: "Filtered for a crisp, pure character — a reliable freezer staple." },
  { slug: "citrus-twist-vodka", name: "Citrus Twist Vodka", category: "vodka", distillery: "Twist & Co.", price: 21, abv: 37.5, volume: "700ml", origin: "USA", rating: 4.2, reviews: 187, stock: 130, palette: { glass: "#1c2410", liquid: "#eef0c8", label: "#d9c43a" }, tags: ["Citrus", "Flavored", "Fun"], tasting: { nose: "Bright lemon and lime zest.", palate: "Zesty citrus, lightly sweet.", finish: "Fresh and tangy." }, notes: ["Lemon", "Lime", "Zest"], pairings: ["Soda", "Lemonade", "Cocktails"], description: "A zesty citrus vodka that makes everyday highballs pop." },

  // ---------- Whisky ----------
  { slug: "old-mill-bourbon", name: "Old Mill Bourbon", category: "whiskey", distillery: "Old Mill Distillery", price: 28, abv: 40, volume: "700ml", origin: "Kentucky, USA", rating: 4.5, reviews: 356, badge: "Best Seller", stock: 95, palette: { glass: "#2a160c", liquid: "#a8521a", label: "#e0b357" }, tags: ["Sweet", "Oaky", "Everyday"], tasting: { nose: "Vanilla, caramel and toasted oak.", palate: "Sweet corn, butterscotch and spice.", finish: "Warm and mellow." }, notes: ["Vanilla", "Caramel", "Oak"], pairings: ["BBQ", "Burgers", "Pecan pie"], description: "A friendly, sweet everyday bourbon — vanilla and caramel without the markup." },
  { slug: "riverside-rye", name: "Riverside Rye", category: "whiskey", distillery: "Riverside Co.", price: 31, abv: 43, volume: "700ml", origin: "Indiana, USA", rating: 4.4, reviews: 241, stock: 80, palette: { glass: "#2a160c", liquid: "#b5601f", label: "#8a3324" }, tags: ["Spicy", "Bold", "Rye"], tasting: { nose: "Peppery rye and dried orchard fruit.", palate: "Spicy, dry and full.", finish: "Long and peppery." }, notes: ["Pepper", "Rye", "Apple"], pairings: ["Manhattan", "Smoked meats", "Cheese"], description: "A spicy, dependable rye for everyday old fashioneds and sippers." },
  { slug: "highland-blend-whisky", name: "Highland Blend Whisky", category: "whiskey", distillery: "Glen Harbour", price: 24, abv: 40, volume: "700ml", origin: "Scotland", rating: 4.3, reviews: 402, stock: 130, palette: { glass: "#2a160c", liquid: "#9a4f1c", label: "#c9a04a" }, tags: ["Smooth", "Blend", "Value"], tasting: { nose: "Honey, light malt and a hint of smoke.", palate: "Smooth, sweet and easy.", finish: "Gentle and warming." }, notes: ["Honey", "Malt", "Smoke"], pairings: ["Soda", "Neat", "Cheese"], description: "A smooth, approachable blended Scotch — an everyday dram that drinks well above its price." },
  { slug: "smoky-peat-whisky", name: "Smoky Peat Whisky", category: "whiskey", distillery: "Isle & Ember", price: 36, abv: 43, volume: "700ml", origin: "Islay, Scotland", rating: 4.6, reviews: 198, stock: 70, palette: { glass: "#1c130a", liquid: "#7a3f14", label: "#3a4a52" }, tags: ["Smoky", "Peaty", "Bold"], tasting: { nose: "Campfire smoke, brine and pepper.", palate: "Peaty, bold and coastal.", finish: "Long, smoky and dry." }, notes: ["Peat", "Smoke", "Brine"], pairings: ["Smoked salmon", "Blue cheese", "Dark chocolate"], description: "A boldly smoky everyday peated whisky for fans of the Islay style." },

  // ---------- Rum ----------
  { slug: "island-gold-rum", name: "Island Gold Rum", category: "rum", distillery: "Bay Coast Rum Co.", price: 18, abv: 37.5, volume: "700ml", origin: "Barbados", rating: 4.3, reviews: 276, stock: 160, palette: { glass: "#1d0f08", liquid: "#a85c1e", label: "#e0b357" }, tags: ["Golden", "Smooth", "Tropical"], tasting: { nose: "Toffee, banana and warm spice.", palate: "Smooth caramel and tropical fruit.", finish: "Mellow and sweet." }, notes: ["Toffee", "Banana", "Spice"], pairings: ["Cola", "Pineapple", "Ginger beer"], description: "A smooth golden rum for everyday cocktails — easy, tropical and affordable." },
  { slug: "spiced-harbor-rum", name: "Spiced Harbor Rum", category: "rum", distillery: "Harbor Spirits", price: 20, abv: 35, volume: "700ml", origin: "Trinidad", rating: 4.4, reviews: 318, badge: "Best Seller", stock: 175, palette: { glass: "#1d0f08", liquid: "#8a4422", label: "#caa13e" }, tags: ["Spiced", "Vanilla", "Warm"], tasting: { nose: "Vanilla, cinnamon and clove.", palate: "Warm spice with sweet caramel.", finish: "Smooth and spiced." }, notes: ["Vanilla", "Cinnamon", "Clove"], pairings: ["Cola", "Apple juice", "Eggnog"], description: "A warm, spiced everyday rum — vanilla and cinnamon made for mixing." },
  { slug: "dark-cove-rum", name: "Dark Cove Rum", category: "rum", distillery: "Cove Distillers", price: 23, abv: 40, volume: "700ml", origin: "Jamaica", rating: 4.5, reviews: 204, stock: 120, palette: { glass: "#140a06", liquid: "#5a2e12", label: "#b5712f" }, tags: ["Dark", "Rich", "Molasses"], tasting: { nose: "Molasses, dark fruit and oak.", palate: "Rich, full and lightly smoky.", finish: "Long and treacly." }, notes: ["Molasses", "Raisin", "Oak"], pairings: ["Ginger beer", "Lime", "Stews"], description: "A rich, dark everyday rum with deep molasses character for hearty cocktails." },

  // ---------- Gin ----------
  { slug: "garden-botanical-gin", name: "Garden Botanical Gin", category: "gin", distillery: "Garden Row", price: 24, abv: 40, volume: "700ml", origin: "England", rating: 4.4, reviews: 287, stock: 110, palette: { glass: "#0f2419", liquid: "#dfeae0", label: "#3f7d63" }, tags: ["Botanical", "Fresh", "Balanced"], tasting: { nose: "Juniper, coriander and fresh herbs.", palate: "Bright botanicals, balanced and crisp.", finish: "Clean and herbal." }, notes: ["Juniper", "Coriander", "Herbs"], pairings: ["Tonic", "Cucumber", "Lime"], description: "A balanced botanical gin for everyday G&Ts — fresh, crisp and versatile." },
  { slug: "london-dry-gin", name: "Classic London Dry Gin", category: "gin", distillery: "Old Square Co.", price: 21, abv: 43, volume: "700ml", origin: "London, England", rating: 4.3, reviews: 344, badge: "Best Seller", stock: 150, palette: { glass: "#0f2419", liquid: "#eaf0ea", label: "#1f4a8a" }, tags: ["Classic", "Juniper", "Dry"], tasting: { nose: "Bold juniper and citrus peel.", palate: "Dry, crisp and classic.", finish: "Sharp and clean." }, notes: ["Juniper", "Citrus", "Pepper"], pairings: ["Tonic", "Martini", "Negroni"], description: "A no-nonsense London dry gin — the dependable backbone of everyday cocktails." },
  { slug: "citrus-grove-gin", name: "Citrus Grove Gin", category: "gin", distillery: "Grove & Co.", price: 27, abv: 40, volume: "700ml", origin: "Spain", rating: 4.5, reviews: 221, stock: 95, palette: { glass: "#1c2410", liquid: "#eef0c8", label: "#d9a93a" }, tags: ["Citrus", "Bright", "Zesty"], tasting: { nose: "Orange, lemon and soft juniper.", palate: "Zesty citrus over a smooth base.", finish: "Bright and refreshing." }, notes: ["Orange", "Lemon", "Juniper"], pairings: ["Tonic", "Soda", "Grapefruit"], description: "A sunny, citrus-forward gin that lifts any everyday highball." },

  // ---------- Tequila ----------
  { slug: "agave-sol-blanco", name: "Agave Sol Blanco", category: "tequila", distillery: "Sol Distillery", price: 26, abv: 38, volume: "700ml", origin: "Jalisco, Mexico", rating: 4.4, reviews: 263, stock: 100, palette: { glass: "#123048", liquid: "#eef4f7", label: "#d9c43a" }, tags: ["Blanco", "Crisp", "Agave"], tasting: { nose: "Fresh agave, citrus and pepper.", palate: "Crisp, clean and peppery.", finish: "Bright and short." }, notes: ["Agave", "Citrus", "Pepper"], pairings: ["Margarita", "Lime", "Soda"], description: "A crisp blanco tequila for everyday margaritas — clean agave at a friendly price." },
  { slug: "casa-verde-reposado", name: "Casa Verde Reposado", category: "tequila", distillery: "Casa Verde", price: 33, abv: 40, volume: "700ml", origin: "Jalisco, Mexico", rating: 4.5, reviews: 198, badge: "Best Seller", stock: 85, palette: { glass: "#123048", liquid: "#d9b86a", label: "#2e7d4a" }, tags: ["Reposado", "Oaked", "Smooth"], tasting: { nose: "Cooked agave, vanilla and light oak.", palate: "Smooth, sweet and gently spiced.", finish: "Warm and rounded." }, notes: ["Agave", "Vanilla", "Oak"], pairings: ["Neat", "Tacos", "Lime"], description: "Rested in oak for a smooth, sippable everyday reposado." },
  { slug: "lime-fields-tequila", name: "Lime Fields Tequila", category: "tequila", distillery: "Fields & Sol", price: 24, abv: 38, volume: "700ml", origin: "Jalisco, Mexico", rating: 4.2, reviews: 154, stock: 120, palette: { glass: "#1c2410", liquid: "#eaf0c2", label: "#4a9a3a" }, tags: ["Zesty", "Mixable", "Fresh"], tasting: { nose: "Lime zest and fresh agave.", palate: "Zesty, light and clean.", finish: "Tangy and crisp." }, notes: ["Lime", "Agave", "Salt"], pairings: ["Margarita", "Paloma", "Soda"], description: "A zesty, mixable tequila built for everyday margaritas and palomas." },

  // ---------- Wine ----------
  { slug: "valley-red-blend", name: "Valley Red Blend", category: "wine", distillery: "Valley Vines", price: 14, abv: 13.5, volume: "750ml", origin: "California, USA", rating: 4.3, reviews: 388, badge: "Best Seller", stock: 200, palette: { glass: "#160810", liquid: "#4a0f1c", label: "#caa05a" }, tags: ["Red", "Smooth", "Easy"], tasting: { nose: "Black cherry, plum and a touch of vanilla.", palate: "Soft, fruity and smooth.", finish: "Round and easy." }, notes: ["Cherry", "Plum", "Vanilla"], pairings: ["Pizza", "Pasta", "Burgers"], description: "A smooth, crowd-pleasing red blend for everyday dinners — fruity and easy." },
  { slug: "coastal-sauvignon-blanc", name: "Coastal Sauvignon Blanc", category: "wine", distillery: "Coastline Cellars", price: 13, abv: 12.5, volume: "750ml", origin: "Marlborough, NZ", rating: 4.4, reviews: 296, stock: 180, palette: { glass: "#1a2410", liquid: "#e8eec0", label: "#3a8a5a" }, tags: ["White", "Crisp", "Zesty"], tasting: { nose: "Passionfruit, lime and fresh grass.", palate: "Crisp, zesty and bright.", finish: "Clean and refreshing." }, notes: ["Passionfruit", "Lime", "Grass"], pairings: ["Salads", "Seafood", "Goat cheese"], description: "A crisp, zesty Sauvignon Blanc — a refreshing everyday white." },
  { slug: "tuscan-table-red", name: "Tuscan Table Red", category: "wine", distillery: "Borgo Vino", price: 12, abv: 13, volume: "750ml", origin: "Tuscany, Italy", rating: 4.2, reviews: 254, stock: 190, palette: { glass: "#160810", liquid: "#5a121f", label: "#c9a04a" }, tags: ["Red", "Rustic", "Food"], tasting: { nose: "Red cherry, herbs and earth.", palate: "Bright acidity with savoury fruit.", finish: "Dry and food-friendly." }, notes: ["Cherry", "Herb", "Earth"], pairings: ["Pasta", "Pizza", "Cured meats"], description: "A rustic, food-friendly Italian red made for everyday pasta nights." },
  { slug: "garnet-merlot", name: "Garnet Merlot", category: "wine", distillery: "Garnet Estate", price: 15, abv: 13.5, volume: "750ml", origin: "Chile", rating: 4.3, reviews: 212, stock: 165, palette: { glass: "#160810", liquid: "#4a0f1a", label: "#a6713c" }, tags: ["Red", "Soft", "Plummy"], tasting: { nose: "Plum, blackberry and mocha.", palate: "Soft, round and velvety.", finish: "Smooth and gentle." }, notes: ["Plum", "Blackberry", "Mocha"], pairings: ["Roast chicken", "Burgers", "Cheese"], description: "A soft, velvety Merlot — easy and smooth for everyday sipping." },
  { slug: "rose-bloom", name: "Rosé Bloom", category: "wine", distillery: "Bloom Vineyards", price: 13, abv: 12.5, volume: "750ml", origin: "Provence, France", rating: 4.4, reviews: 277, badge: "New", stock: 175, palette: { glass: "#1a0c10", liquid: "#f0c8cc", label: "#d98a9a" }, tags: ["Rosé", "Dry", "Fresh"], tasting: { nose: "Strawberry, melon and citrus blossom.", palate: "Dry, fresh and delicate.", finish: "Crisp and clean." }, notes: ["Strawberry", "Melon", "Citrus"], pairings: ["Salads", "Grilled fish", "Brunch"], description: "A dry, delicate rosé for everyday afternoons — fresh, pink and easy." },
  { slug: "oak-ridge-chardonnay", name: "Oak Ridge Chardonnay", category: "wine", distillery: "Oak Ridge", price: 14, abv: 13, volume: "750ml", origin: "California, USA", rating: 4.2, reviews: 188, stock: 160, palette: { glass: "#1a2410", liquid: "#ecdf9a", label: "#caa13e" }, tags: ["White", "Buttery", "Round"], tasting: { nose: "Apple, pear and light vanilla oak.", palate: "Round, buttery and smooth.", finish: "Soft and creamy." }, notes: ["Apple", "Pear", "Vanilla"], pairings: ["Chicken", "Pasta", "Brie"], description: "A round, lightly oaked Chardonnay — a smooth, everyday white." },
  { slug: "midnight-cabernet", name: "Midnight Cabernet", category: "wine", distillery: "Midnight Cellars", price: 16, abv: 14, volume: "750ml", origin: "Australia", rating: 4.5, reviews: 233, stock: 145, palette: { glass: "#140810", liquid: "#3a0f18", label: "#8a3324" }, tags: ["Red", "Bold", "Cabernet"], tasting: { nose: "Blackcurrant, cedar and dark chocolate.", palate: "Bold, structured and rich.", finish: "Long and firm." }, notes: ["Blackcurrant", "Cedar", "Chocolate"], pairings: ["Steak", "Lamb", "Hard cheese"], description: "A bold, structured Cabernet that punches above its everyday price." },
];

// Every standard product carries 4 background-removed photos + a slideshow
// video, hosted on Cloudinary (see scripts/upload-standard-cloudinary.ts →
// standard-media.ts). Falls back to the local /public copies if a slug is
// somehow missing from the map.
const mediaFor = (slug: string) => {
  const m = STANDARD_MEDIA[slug];
  return {
    images: m?.images ?? [],
    video: m?.video ?? undefined,
  };
};

export const standardProducts: Product[] = raw.map((r, i) => ({
  id: `s${i + 1}`,
  ...r,
  categoryLabel: LABELS[r.category],
  images: r.images ?? mediaFor(r.slug).images,
  video: r.video ?? mediaFor(r.slug).video,
  segment: "STANDARD",
}));
