import { ImageResponse } from "next/og";

// Branded social-share card (Open Graph + Twitter). Generated by Next from
// this file — no external asset, works offline.
export const alt = "BottleExpress — Premium Spirits, Whiskey & Wine Delivered";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function Image() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: "90px",
          background: "#0b0b0f",
          backgroundImage:
            "radial-gradient(900px 500px at 75% -10%, rgba(200,162,75,0.22), transparent 60%), radial-gradient(700px 500px at 0% 120%, rgba(110,31,46,0.18), transparent 55%)",
          color: "#f5f1e8",
          fontFamily: "sans-serif",
        }}
      >
        {/* brand mark: simple bottle glyph */}
        <div style={{ display: "flex", alignItems: "center", gap: "18px" }}>
          <div
            style={{
              display: "flex",
              width: "30px",
              height: "52px",
              borderRadius: "8px",
              border: "3px solid #c8a24b",
              borderTopLeftRadius: "3px",
              borderTopRightRadius: "3px",
            }}
          />
          <div
            style={{
              fontSize: "26px",
              letterSpacing: "10px",
              textTransform: "uppercase",
              color: "#c8a24b",
            }}
          >
            Premium Spirits Delivery
          </div>
        </div>

        <div
          style={{
            display: "flex",
            marginTop: "34px",
            fontSize: "104px",
            fontWeight: 700,
            letterSpacing: "-2px",
            color: "#e3c270",
            lineHeight: 1,
          }}
        >
          BottleExpress
        </div>

        <div
          style={{
            display: "flex",
            marginTop: "30px",
            maxWidth: "820px",
            fontSize: "36px",
            lineHeight: 1.35,
            color: "#d9d3c4",
          }}
        >
          The world&apos;s finest whiskey, wine, champagne and rare spirits —
          authenticated and delivered with concierge care.
        </div>

        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "14px",
            marginTop: "48px",
            fontSize: "24px",
            color: "#8d8779",
          }}
        >
          <div
            style={{
              width: "10px",
              height: "10px",
              borderRadius: "50%",
              background: "#c8a24b",
              display: "flex",
            }}
          />
          Same-day delivery · 21+ verified · Free over $50
        </div>
      </div>
    ),
    { ...size }
  );
}
