/**
 * Upload the local standard-storefront media (transparent PNGs + slideshow
 * MP4s in public/bottles/standard/) to Cloudinary, then emit a TS map of the
 * resulting secure URLs to src/lib/standard-media.ts.
 *
 * Run inside the app container (it has the cloudinary SDK + tsx):
 *   CLOUDINARY_* env vars must be set.
 *   OUT_FILE overrides the output path (default src/lib/standard-media.ts).
 */
import { v2 as cloudinary } from "cloudinary";
import fs from "node:fs";
import path from "node:path";

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
  secure: true,
});

const DIR = "public/bottles/standard";
const OUT = process.env.OUT_FILE || "src/lib/standard-media.ts";
const FOLDER = "nocturne/standard";

async function upload(
  file: string,
  type: "image" | "video",
  publicId: string
): Promise<string> {
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const res = await cloudinary.uploader.upload(path.join(DIR, file), {
        resource_type: type,
        public_id: `${FOLDER}/${publicId}`,
        overwrite: true,
        invalidate: true,
      });
      return res.secure_url;
    } catch (e) {
      if (attempt === 3) throw e;
      await new Promise((r) => setTimeout(r, 1500));
    }
  }
  throw new Error("unreachable");
}

async function main() {
  const files = new Set(fs.readdirSync(DIR));
  const slugs = [...files]
    .filter((f) => f.endsWith(".mp4"))
    .map((f) => f.replace(/\.mp4$/, ""))
    .sort();

  const map: Record<string, { images: string[]; video: string | null }> = {};
  let n = 0;
  for (const slug of slugs) {
    const imgFiles = [
      `${slug}.png`,
      `${slug}-2.png`,
      `${slug}-3.png`,
      `${slug}-4.png`,
    ].filter((f) => files.has(f));

    const images: string[] = [];
    for (const f of imgFiles) {
      images.push(await upload(f, "image", f.replace(/\.png$/, "")));
    }

    let video: string | null = null;
    if (files.has(`${slug}.mp4`)) {
      video = await upload(`${slug}.mp4`, "video", slug);
    }

    map[slug] = { images, video };
    n++;
    console.log(`[${n}/${slugs.length}] ${slug} — ${images.length} img + ${video ? "1 vid" : "no vid"}`);
  }

  const body = `// AUTO-GENERATED by scripts/upload-standard-cloudinary.ts
// Cloudinary secure URLs for the standard-storefront media. Do not edit by hand.
export const STANDARD_MEDIA: Record<
  string,
  { images: string[]; video: string | null }
> = ${JSON.stringify(map, null, 2)};
`;
  fs.writeFileSync(OUT, body);
  console.log(`\nWrote ${OUT} with ${Object.keys(map).length} products.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
